// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzUCVdl0FiYO24BazMUNJiiRv0k7HXNsY',
    appId: '1:404709974622:web:2499e0e8dd764192624acf',
    messagingSenderId: '404709974622',
    projectId: 'finance-app-b314b',
    authDomain: 'finance-app-b314b.firebaseapp.com',
    storageBucket: 'finance-app-b314b.firebasestorage.app',
    measurementId: 'G-QVHM1Y118G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArFTociFAHTkF7JbOd0vgQAvmqU1x7Zm0',
    appId: '1:404709974622:android:f5c488c09403babd624acf',
    messagingSenderId: '404709974622',
    projectId: 'finance-app-b314b',
    storageBucket: 'finance-app-b314b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAbf8qcT7ZBdx5MzkSuwDEfY7HDz7xVbs',
    appId: '1:404709974622:ios:2f5e68f4c3e33191624acf',
    messagingSenderId: '404709974622',
    projectId: 'finance-app-b314b',
    storageBucket: 'finance-app-b314b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAbf8qcT7ZBdx5MzkSuwDEfY7HDz7xVbs',
    appId: '1:404709974622:ios:2f5e68f4c3e33191624acf',
    messagingSenderId: '404709974622',
    projectId: 'finance-app-b314b',
    storageBucket: 'finance-app-b314b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzUCVdl0FiYO24BazMUNJiiRv0k7HXNsY',
    appId: '1:404709974622:web:11b735fcdd3cd873624acf',
    messagingSenderId: '404709974622',
    projectId: 'finance-app-b314b',
    authDomain: 'finance-app-b314b.firebaseapp.com',
    storageBucket: 'finance-app-b314b.firebasestorage.app',
    measurementId: 'G-J1TBG99EM6',
  );
}
